name: Snyk Delta on Commit Changes

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main # Or your main branch

jobs:
  snyk_delta_check:
    name: Snyk Delta Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Needed to compare with the previous commit

    - name: Set up Node.js (if needed)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

   # - name: Set up .NET (if needed)
   #   uses: actions/setup-dotnet@v3
   #   with:
   #      dotnet-version: '8.0.x'

    # - name: Restore dependencies (if needed)
    #   run: |
    #     # Your dependency restoration commands

    - name: Install Snyk CLI
      run: |
        curl -Lo ./snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        sudo mv ./snyk /usr/local/bin/

    - name: Snyk Auth
      run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

    - name: Run Snyk Test on Previous Commit
      id: snyk_base
      run: |
        git checkout HEAD^1
        snyk test --json --print-deps > snyk_base.json
        git checkout HEAD # Switch back to the current commit
      continue-on-error: true # Allow if no previous commit

    - name: Run Snyk Test on Current Commit
      id: snyk_head
      run: snyk test --json --print-deps > snyk_head.json

    - name: Install snyk-delta
      run: npm install -g snyk-delta

    - name: Run Snyk Delta
      run: |
        export SNYK_TOKEN="${{ secrets.SNYK_API_TOKEN }}"
        if [ -f "snyk_base.json" ]; then
          npx snyk-delta --baselineFile snyk_base.json --currentFile snyk_head.json --fail-on=upgradable
        else
          echo "No previous commit found or Snyk test on previous commit failed. Skipping delta analysis."
        fi
