name: Snyk Scan


#on: workflow_dispatch
on: workflow_dispatch
  

jobs:
  snyk-sca:
    name: Snyk SCA Scan
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
          ref: ${{ github.sha }} # Checkout the specific commit that triggered the push
          token: ${{ secrets.GITHUB_TOKEN }}
          #path: instrument-software

    - uses: actions/setup-node@v4
      with:
          node-version: '20'

   # - name: Install libicu dependency
    #  run: |
     #   dnf install -y libicu

  #  - name: Setup .NET
  #    uses: actions/setup-dotnet@v3
  #    with:
  #      dotnet-version: '8.0.x'

  #  - name: Restore dependencies
  #    run: |
  #        find . -name "*.csproj" -regextype egrep -and -not -regex ".*(T|t)est.*|.*(S|s)imulat.*|.*node_modules.*|.*sample.*|.*code-generators.*|.*(A|a)utomat.*" -exec sh -c 'dotnet restore "$0" --use-lock-file' {} \;

    - name: Install Snyk CLI
      run: |
        curl -Lo ./snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/

    - name: Install snyk-to-html
      run: |
        curl -Lo ./snyk-to-html https://github.com/snyk/snyk-to-html/releases/latest/download/snyk-to-html-linux
        chmod +x ./snyk-to-html
        mv ./snyk-to-html /usr/local/bin/

    - name: SNYK auth
      run: |
        snyk auth ${{secrets.SNYK_API_TOKEN}}


    - name: Install snyk-delta
      run: |
        curl -Lo ./snyk-delta https://github.com/snyk-labs/snyk-delta/releases/latest/download/snyk-delta-linux
        chmod +x ./snyk-delta
        mv ./snyk-delta /usr/local/bin/



    - name: Run Snyk Delta on Changed Files
      run: |
        # Get the previous commit hash
        PREVIOUS_COMMIT=$(git rev-parse HEAD^1)
        echo "Previous Commit: $PREVIOUS_COMMIT"
        echo "Exit Code: $?"
    
        # Get the list of modified files since the previous commit
        git diff --name-only "$PREVIOUS_COMMIT" HEAD > changed_files.txt
        echo "Exit Code: $?"
    
        # Filter for relevant files ...
        grep -E '\.(csproj|sln|lock|json|yml)$' changed_files.txt > relevant_changed_files.txt
        echo "Exit Code: $?"
    
        if [ -s "relevant_changed_files.txt" ]; then
          echo "Running Snyk Delta on the following changed files since commit $PREVIOUS_COMMIT:"
          cat relevant_changed_files.txt
          while IFS= read -r file; do
            echo "Scanning delta for: $file"
            output=$(snyk delta --file="$file" --org=*** --base="$PREVIOUS_COMMIT" HEAD)
            echo "Snyk Delta Output for $file:"
            echo "$output"
            exit_code=$?
            echo "Snyk Delta Exit Code: $exit_code"
            if [ $exit_code -ne 0 ]; then
              echo "Snyk Delta found issues or encountered an error for $file."
            fi
          done < "relevant_changed_files.txt"
        else
          echo "No relevant files changed in this push for Snyk Delta analysis."
        fi


          

